version: "3"
services:
  www:
    build: 
      context: .
      dockerfile: ./www/Dockerfile
    ports:
      - "8080:80"

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "9090:80"
